# Adapted from:
# https://github.com/VaultVulp/gp-docker-action#complete-workflow-example
name: Build and publish

on: [push, pull_request]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: mitre/growthcleanr
          image-tag: ${{ github.event.pull_request.head.ref }}
